# Generated by Django 4.1.6 on 2024-02-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Families',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=25)),
                ('family_pic', models.ImageField(blank=True, default='', null=True, upload_to='families_pics')),
                ('name1', models.CharField(max_length=25)),
                ('name2', models.CharField(max_length=25)),
            ],
        ),
    ]
