# Generated by Django 4.1.6 on 2024-02-18 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardingList',
            fields=[
                ('guard_list_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(default='', max_length=100, unique=True)),
                ('how_many_guards', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Families',
            fields=[
                ('family_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('family_name', models.CharField(default='', max_length=100)),
                ('family_pic', models.ImageField(blank=True, default='', null=True, upload_to='families_pics')),
                ('name1', models.CharField(max_length=25)),
                ('phone1', models.CharField(default='', max_length=25, unique=True)),
                ('armed1', models.BooleanField(default=False)),
                ('name2', models.CharField(blank=True, max_length=25, null=True)),
                ('phone2', models.CharField(blank=True, max_length=25, null=True)),
                ('armed2', models.BooleanField(default=False)),
                ('id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmbe.userrole')),
            ],
        ),
    ]
