# Generated by Django 4.1.6 on 2024-02-25 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDetails',
            fields=[
                ('shift_details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hour', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='guardinglist',
            old_name='guard_list_id',
            new_name='guarding_list_id',
        ),
        migrations.AlterField(
            model_name='position',
            name='how_many_guards',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default='NO GUARDS'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('family_id', models.ManyToManyField(related_name='shift_family_id', to='gmbe.families')),
                ('shift_details_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shift_shift_details_id', to='gmbe.shiftdetails')),
            ],
        ),
        migrations.CreateModel(
            name='GlistDetails',
            fields=[
                ('glist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('list_date', models.DateField(default=django.utils.timezone.now)),
                ('list_day', models.CharField(default='', max_length=10)),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glistdetails_position_id', to='gmbe.position')),
            ],
        ),
        migrations.AddField(
            model_name='guardinglist',
            name='glist_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='glistdetails_position_id', to='gmbe.glistdetails'),
        ),
        migrations.AddField(
            model_name='guardinglist',
            name='shifts',
            field=models.ManyToManyField(default='NO SHIFTS', related_name='guardinglist_shifts', to='gmbe.shift'),
        ),
    ]
