# Generated by Django 4.1.6 on 2024-02-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='families',
            name='armed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='families',
            name='phone1',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='families',
            name='phone2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='families',
            name='name2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
