# Generated by Django 4.1.6 on 2024-02-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0002_shiftdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetGuardingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_date', models.CharField(default='', max_length=15)),
                ('list_day', models.CharField(default='', max_length=15)),
                ('position_id', models.IntegerField(default='', max_length=15)),
                ('shifts', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
