# Generated by Django 4.1.6 on 2024-02-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0002_families_armed_families_phone1_families_phone2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stance',
            fields=[
                ('stance_id', models.AutoField(primary_key=True, serialize=False)),
                ('stance_name', models.CharField(default='', max_length=100)),
                ('shift_hours', models.IntegerField(choices=[(1, 'שעה אחת'), (2, 'שעתיים'), (3, '3 שעות'), (4, 'שעות 4'), (5, 'שעות 6'), (6, 'שעות 8'), (7, 'שעות 12'), (8, 'שעות 24')])),
                ('how_many_guards', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
            ],
        ),
        migrations.AlterField(
            model_name='families',
            name='family_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='families',
            name='phone1',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
    ]
