# Generated by Django 4.1.6 on 2024-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0003_setguardinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setguardinglist',
            name='position_id',
            field=models.IntegerField(default=''),
        ),
    ]
