# Generated by Django 4.1.6 on 2024-02-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0003_stance_alter_families_family_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stance',
            name='stance_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
