# Generated by Django 4.1.6 on 2024-03-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0004_alter_setguardinglist_position_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='how_many_guards',
        ),
    ]
