# Generated by Django 4.1.6 on 2024-02-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0004_alter_stance_stance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardingList',
            fields=[
                ('guard_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=20)),
                ('day', models.CharField(default='', max_length=10)),
                ('time', models.CharField(default='', max_length=10)),
                ('armed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armed_guarding_lists', to='gmbe.families')),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_id_guarding_lists', to='gmbe.families')),
                ('family_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_name_guarding_lists', to='gmbe.families')),
                ('family_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_pic_guarding_lists', to='gmbe.families')),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name1_guarding_lists', to='gmbe.families')),
                ('name2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name2_guarding_lists', to='gmbe.families')),
                ('phone1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone1_guarding_lists', to='gmbe.families')),
                ('phone2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone2_guarding_lists', to='gmbe.families')),
                ('stance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stance_id_guarding_lists', to='gmbe.stance')),
                ('stance_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stance_name_guarding_lists', to='gmbe.stance')),
            ],
        ),
    ]
