# Generated by Django 4.1.6 on 2024-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0005_remove_position_how_many_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setguardinglist',
            name='shifts',
            field=models.TextField(default=''),
        ),
    ]
