# Generated by Django 4.1.6 on 2024-02-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0005_guardinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='families',
            name='armed',
        ),
        migrations.RemoveField(
            model_name='guardinglist',
            name='armed',
        ),
        migrations.AddField(
            model_name='families',
            name='armed1',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='families',
            name='armed2',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='guardinglist',
            name='armed1',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='armed1_guarding_lists', to='gmbe.families'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardinglist',
            name='armed2',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='armed2_guarding_lists', to='gmbe.families'),
            preserve_default=False,
        ),
    ]
