# Generated by Django 4.1.6 on 2024-02-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0006_remove_families_armed_remove_guardinglist_armed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='families',
            name='armed1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='families',
            name='armed2',
            field=models.BooleanField(default=False),
        ),
    ]
