# Generated by Django 4.1.6 on 2024-03-19 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0007_alter_guardinglist_glist_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardinglist',
            name='glist_id',
        ),
        migrations.AddField(
            model_name='guardinglist',
            name='position_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='glistdetails_position_id', to='gmbe.position'),
        ),
        migrations.AddField(
            model_name='shiftdetails',
            name='shift_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shiftdetails',
            name='shift_day',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='GlistDetails',
        ),
    ]
