# Generated by Django 4.1.6 on 2024-02-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0007_alter_families_armed1_alter_families_armed2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='families',
            name='armed1',
        ),
        migrations.RemoveField(
            model_name='families',
            name='armed2',
        ),
        migrations.RemoveField(
            model_name='guardinglist',
            name='armed1',
        ),
        migrations.RemoveField(
            model_name='guardinglist',
            name='armed2',
        ),
    ]
