# Generated by Django 4.1.6 on 2024-03-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0008_remove_guardinglist_glist_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftdetails',
            old_name='hour',
            new_name='shift_hour',
        ),
    ]
