# Generated by Django 4.1.6 on 2024-03-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0009_rename_hour_shiftdetails_shift_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardinglist',
            name='position_id',
        ),
        migrations.AddField(
            model_name='shiftdetails',
            name='position_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='glistdetails_position_id', to='gmbe.position'),
        ),
    ]
