# Generated by Django 4.1.6 on 2024-02-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0009_families_armed1_families_armed2_guardinglist_armed1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='families',
            name='family_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guardinglist',
            name='guard_list_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stance',
            name='stance_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmbe.userrole')),
            ],
        ),
        migrations.AddField(
            model_name='families',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmbe.users'),
        ),
        migrations.AddField(
            model_name='guardinglist',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_guarding_lists', to='gmbe.users'),
        ),
    ]
