# Generated by Django 4.1.6 on 2024-02-11 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmbe', '0010_userrole_alter_families_family_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='families',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='guardinglist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='families',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardinglist',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_guarding_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
