# Generated by Django 4.1.6 on 2024-03-21 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0010_remove_guardinglist_position_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_details_id',
        ),
        migrations.AddField(
            model_name='guardinglist',
            name='glist_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='guardinglist',
            name='glist_position_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='GuardingList_position_id', to='gmbe.position'),
        ),
        migrations.AddField(
            model_name='shift',
            name='position_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Shift_position_id', to='gmbe.position'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_day',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_hour',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='ShiftDetails',
        ),
    ]
