# Generated by Django 4.1.6 on 2024-03-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0011_remove_shift_shift_details_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardinglist',
            name='last_guard_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
