# Generated by Django 4.1.6 on 2024-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0013_alter_guardinglist_last_guard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardinglist',
            name='glist_day',
            field=models.CharField(default='', max_length=10),
        ),
    ]
