# Generated by Django 4.1.6 on 2024-03-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0014_guardinglist_glist_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardinglist',
            name='glist_day',
        ),
    ]
