# Generated by Django 4.1.6 on 2024-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0015_remove_guardinglist_glist_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardinglist',
            name='glist_day',
            field=models.CharField(default='', max_length=10),
        ),
    ]
