# Generated by Django 4.1.6 on 2024-05-12 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0016_guardinglist_glist_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='setguardinglist',
            name='last_guard_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='SetGuardingList_last_guard_id', to='gmbe.families'),
        ),
    ]
