# Generated by Django 4.1.6 on 2024-05-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0017_setguardinglist_last_guard_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('exchange_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exchange_date', models.CharField(default='', max_length=15)),
                ('exchange_day', models.CharField(default='', max_length=15)),
                ('exchange_hour', models.CharField(default='', max_length=8)),
                ('exchange_type', models.CharField(default='', max_length=8)),
                ('origin_guard_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Exchanges_origin_guard_id', to='gmbe.families')),
                ('substitute_guard_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Exchanges_substitute_guard_id', to='gmbe.families')),
            ],
        ),
    ]
