# Generated by Django 4.1.6 on 2024-05-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0018_exchanges'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidGuards',
            fields=[
                ('paid_guard_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pguard_name', models.CharField(default='', max_length=100)),
                ('puard_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('puard_family_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='PaidGuards_family_id', to='gmbe.families')),
            ],
        ),
    ]
