# Generated by Django 4.1.6 on 2024-05-28 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0020_exchanges_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='shift_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Exchanges_shift_id', to='gmbe.shift'),
        ),
    ]
