# Generated by Django 4.1.6 on 2024-06-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0022_rename_puard_family_id_paidguards_pguard_family_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaidGuards',
        ),
    ]
