# Generated by Django 4.1.6 on 2024-06-04 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmbe', '0023_delete_paidguards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='families',
            old_name='id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='families',
            name='role_name',
        ),
        migrations.AddField(
            model_name='families',
            name='family_pic2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='families_pics'),
        ),
        migrations.AddField(
            model_name='families',
            name='pguard_armed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='families',
            name='pguard_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='families',
            name='pguard_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='families',
            name='pguard_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='families_pics'),
        ),
        migrations.CreateModel(
            name='PaidGuards',
            fields=[
                ('pguard_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pguard_family_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pguard_family_id', to='gmbe.families')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_role', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Custom_user_role', to='gmbe.userrole')),
            ],
        ),
    ]
