# Generated by Django 4.1.6 on 2024-06-09 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0024_rename_id_families_user_remove_families_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='families',
            name='armed1',
        ),
        migrations.RemoveField(
            model_name='families',
            name='armed2',
        ),
        migrations.RemoveField(
            model_name='families',
            name='family_pic',
        ),
        migrations.RemoveField(
            model_name='families',
            name='family_pic2',
        ),
        migrations.RemoveField(
            model_name='families',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='families',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='families',
            name='pguard_armed',
        ),
        migrations.RemoveField(
            model_name='families',
            name='pguard_name',
        ),
        migrations.RemoveField(
            model_name='families',
            name='pguard_phone',
        ),
        migrations.RemoveField(
            model_name='families',
            name='pguard_pic',
        ),
        migrations.RemoveField(
            model_name='families',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='families',
            name='phone2',
        ),
        migrations.AddField(
            model_name='paidguards',
            name='armed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paidguards',
            name='pguard_email',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='paidguards',
            name='pguard_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paidguards',
            name='pguard_phone',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='paidguards',
            name='pguard_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='families_pics'),
        ),
        migrations.CreateModel(
            name='Fguard',
            fields=[
                ('fguard_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fguard_name', models.CharField(default='', max_length=100)),
                ('fguard_phone', models.CharField(default='', max_length=25, unique=True)),
                ('fguard_email', models.EmailField(default='', max_length=200, unique=True)),
                ('armed', models.BooleanField(default=False)),
                ('fguard_pic', models.ImageField(blank=True, default='', null=True, upload_to='families_pics')),
                ('family_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fguard_family_id', to='gmbe.families')),
            ],
        ),
    ]
