# Generated by Django 4.1.6 on 2024-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0025_remove_families_armed1_remove_families_armed2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidguards',
            old_name='pguard_family_id',
            new_name='family_id',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='family_id',
        ),
        migrations.AddField(
            model_name='shift',
            name='fguard_id',
            field=models.ManyToManyField(related_name='shift_fguard_id', to='gmbe.fguard'),
        ),
        migrations.AddField(
            model_name='shift',
            name='pguard_id',
            field=models.ManyToManyField(related_name='shift_pguard_id', to='gmbe.paidguards'),
        ),
    ]
