# Generated by Django 4.1.6 on 2024-06-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0026_rename_pguard_family_id_paidguards_family_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges',
            name='origin_guard_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Exchanges_origin_guard_id', to='gmbe.fguard'),
        ),
        migrations.AlterField(
            model_name='exchanges',
            name='substitute_guard_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Exchanges_substitute_guard_id', to='gmbe.fguard'),
        ),
    ]
