# Generated by Django 4.1.6 on 2024-06-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0027_alter_exchanges_origin_guard_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchanges',
            old_name='substitute_guard_id',
            new_name='substitute_fguard_id',
        ),
        migrations.AddField(
            model_name='exchanges',
            name='substitute_Pguard_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Exchanges_substitute_Pguard_id', to='gmbe.paidguards'),
        ),
    ]
