# Generated by Django 4.1.6 on 2024-06-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0028_rename_substitute_guard_id_exchanges_substitute_fguard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges',
            name='substitute_Pguard_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exchanges_substitute_Pguard_id', to='gmbe.paidguards'),
        ),
        migrations.AlterField(
            model_name='exchanges',
            name='substitute_fguard_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exchanges_substitute_guard_id', to='gmbe.fguard'),
        ),
    ]
