# Generated by Django 4.1.6 on 2024-06-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbe', '0029_alter_exchanges_substitute_pguard_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
